controllers/HotelApisController.php
<?php

namespace app\controllers;

use Yii;
use app\models\HotelApis;
use app\models\HotelApisSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * HotelApisController implements the CRUD actions for HotelApis model.
 */
class HotelApisController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all HotelApis models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new HotelApisSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single HotelApis model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new HotelApis model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new HotelApis();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->hotel_apis_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing HotelApis model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->hotel_apis_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing HotelApis model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the HotelApis model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return HotelApis the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = HotelApis::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/WebApiController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use GuzzleHttp\Client;
use yii\helpers\Json;
use app\models\HotelApis;
use app\models\SyncForm;
use yii\helpers\Html;

class WebApiController extends Controller {

    /**
     * @return array
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['sync-to-zhavroad-by-webhook'], // add all actions to take guest to login page
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'sync-to-zhavroad-by-webhook' => ['POST']
                ],
            ],
        ];
    }
    public function beforeAction($action)
    {
        if (in_array($action->id, ['sync-to-zhavroad-by-webhook'])) {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }
    /**
     * @param int $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionTestConnection(int $id) {
        $model = $this->findModel($id);
        if (!empty($model->beds24_room_map)) {
            $beds24_information = Json::decode($model->beds24_room_map, true);
            if (!isset($beds24_information['beds24_authentication'])) {
                return $this->asJson(['success' => false, "error" => "", "errorCode" => ""]);
            }
            $authentication = $beds24_information['beds24_authentication'];
            $auth = array();
            $auth['apiKey'] = $authentication['apiKey'];
            $auth['propKey'] = $authentication['propKey'];
            $data = array();
            $data['authentication'] = $auth;
            $client = new Client();
            $res = $client->request('POST', 'https://api.beds24.com/json/getPropertyContent', [
                'body' => json_encode($data)
            ]);
            if ($res->getStatusCode() == 200) {
                $result = $res->getBody()->getContents();
                $info = json_decode($result, true);
                if (isset($info['error'])) {
                    $info['success'] = false;
                    return $this->asJson($info);
                } else {
                    return $this->asJson(['success' => true, "error" => "", "errorCode" => ""]);
                }
            } else {
                return $this->asJson(['success' => false, "error" => "", "errorCode" => $res->getStatusCode()]);
            }
        } else {
            return $this->asJson(['success' => false, "error" => "", "errorCode" => ""]);
        }
    }
    
    /**
     * Sync zhavroad platform with beds24
     * @param int $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionSync(int $id) {
        $hotel_api = $this->findModel($id);
        if($hotel_api->status == 'inactive') {
            throw new NotFoundHttpException('The property is inactive');
        }
        $beds24_room_map = $hotel_api->beds24_room_map;
        $rooms = [];
        $res = [];
        $model = new SyncForm;
        if (!empty($beds24_room_map)) {
            $beds24_information = Json::decode($hotel_api->beds24_room_map, true);
            if (!isset($beds24_information['beds24_authentication'])) {
                throw new NotFoundHttpException('authentication information is not set!');
            }
            if (!isset($beds24_information['rooms'])) {
                throw new NotFoundHttpException('rooms information is not complete!');
            }
            $rooms = $beds24_information['rooms'];
            $newRoomsValues = Yii::$app->Beds24Api->getRoomNamesFromZhavroadOTA($rooms);
            if ($model->load(Yii::$app->request->post())) {
                if (isset($_POST['get-from-beds24'])) {
                    return $this->_getFromBeds24($rooms, $model, $beds24_information, $hotel_api);
                } elseif (isset($_POST['set-to-Beds24']) && $model->validate()) {
                    return $this->_setToBeds24($rooms, $model, $beds24_information, $hotel_api);
                }
            }
            return $this->render('sync-form', ['model' => $model, 'rooms' => $newRoomsValues]);
        }
        throw new NotFoundHttpException('beds24 room map field is not set!');
    }
    /**
     * action to sync availability from beds24 to Zhavroad when beds24 webhook call
     */
    public function actionSyncToZhavroadByWebhook() {
        foreach (Yii::$app->request->post() as $k=>$v){
            $post = json_decode($k,true);
        }
        if(!empty($post) && isset($post['roomId']) && isset($post['propId']) && isset($post['ownerId'])){
            $roomId = $post['roomId'];
            $propId = $post['propId'];
            $ownerId = $post['ownerId'];
            $SQL = 'SELECT `hotel_id`, `beds24_room_map`,`status` FROM hotel_apis WHERE JSON_EXTRACT(`beds24_room_map`, "$.propId","$.ownerId") = JSON_ARRAY(:prop_id,:ownerId)';
            $resultQuery = Yii::$app->db->createCommand($SQL)->bindValue(':prop_id', $propId)->bindValue(':ownerId', $ownerId)->queryOne();
            if($resultQuery != 0 && ($resultQuery['status'] == 'active') ){          
                $beds24_information = json_decode($resultQuery['beds24_room_map'],true);
                $rooms = $beds24_information['rooms'];
                $zhavroadRoomNumber = $rooms[$roomId];
                $priceRate = Yii::$app->Beds24Api->getPriceRate($beds24_information, $roomId);
                $model = new SyncForm(['scenario' => SyncForm::SCENARIO_WEBHOOK_FOR_ZHAVROAD_SYNC]);
                $model->roomId = $roomId;
                $from = date('Ymd', time());
                $to = date('Ymd', strtotime('+1 year'));
                $res = $model->Beds24GetRoomDates($beds24_information, $from, $to);
                if($res['success'] === true) {
                    $msg = Yii::$app->Beds24Api->updateZhavroad($res['info'], $zhavroadRoomNumber, $resultQuery['hotel_id'], $priceRate);
                    Yii::error($msg);
                }else{
                    Yii::error($res);
                }
            }else{
                Yii::error('have error in sql with propId '. Html::encode($propId). ' and owenerId '. Html::encode($ownerId) . 'or the property is inactive');
            }
        }
    }
    /**
     * 
     * @param array $rooms
     * @param SyncForm $model
     * @param array $beds24_information
     * @param HotelApis $hotel_api
     * @return \yii\web\Response
     */
    private function _getFromBeds24(array $rooms, SyncForm $model, array $beds24_information, HotelApis $hotel_api) {
        $res = $model->syncFromBeds24($beds24_information);
        // sync form result
        return $this->_syncFormResult($res, $rooms, $model, $beds24_information, $hotel_api);
    }
    /**
     * 
     * @param array $rooms
     * @param SyncForm $model
     * @param array $beds24_information
     * @param HotelApis $hotel_api
     * @return \yii\web\Response
     */
    private function _setToBeds24(array $rooms,SyncForm $model,array $beds24_information, HotelApis $hotel_api) {
        $zhavroadRoomNumber = $rooms[$model->roomId];
        $priceRate = Yii::$app->Beds24Api->getPriceRate($beds24_information, $model->roomId);
        $zhavroadRoomsAvailibility = Yii::$app->Beds24Api->getRoomsDatesFromZhavroad($zhavroadRoomNumber,$hotel_api->hotel_id,$model->from,$model->to,$priceRate);
        $msg = $model->Beds24SetRoomDates($beds24_information,$zhavroadRoomsAvailibility);
        return $this->render('sync-form-result', ['model' => $model, 'res' => $msg]);        
    }
    /**
     * SyncForm model load result 
     * @param type $res
     * @param type $rooms
     * @param type $model
     * @param type $beds24_information
     * @param type $hotel_api
     * @return \yii\web\Response
     */
    private function _syncFormResult($res, $rooms, $model, $beds24_information, $hotel_api) {
        if (isset($res['success']) && $res['success']) {
            $zhavroadRoomNumber = $rooms[$model->roomId];
            $priceRate = Yii::$app->Beds24Api->getPriceRate($beds24_information, $model->roomId);
            $msg = Yii::$app->Beds24Api->updateZhavroad($res['info'], $zhavroadRoomNumber, $hotel_api->hotel_id, $priceRate);
            return $this->render('sync-form-result', ['model' => $model, 'res' => $msg]);
        }
        return $this->render('sync-form-result', ['model' => $model, 'res' => $res]);
    }

    /**
     * Finds the HotelApis model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return HotelApis the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel(int $id) {
        if (($model = HotelApis::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

views/hotel-apis/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model app\models\HotelApis */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="hotel-apis-form">
    <div id="msg">
    </div>
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'hotel_id')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'hotel_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'api_key')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'beds24_room_map')->textarea(['rows' => '12']) ?>
    
    <?= $form->field($model, 'status')->dropDownList(
            [
                'active'=> Yii::t('app', 'Active'),
                'inactive'=> Yii::t('app', 'Inactive'),
            ]
            ) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
        <?php
        if (!$model->isNewRecord) {
            ?>
            <?= Html::a('Test Connection', '#', ['class' => 'btn btn-info', "id" => "connection-test"]) ?>
            <?php
        }
        ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php
$url = Url::to(['web-api/test-connection','id'=> $model->hotel_apis_id ],true);
$JS = <<<EOL
    $(document).ready(function () {
        $(document).ajaxStart(function(){
            $("#connection-test").attr("disabled", true);
        });
        $(document).ajaxComplete(function(){
            $("#connection-test").attr("disabled", false);
        });
        $("#connection-test").on("click", function(){
            $.ajax({
                type: "GET",
                url: "$url",
                success: function (data) {
                    if(data.success == true){
                        $('#msg').html(
                            `<div class="alert alert-success" role="alert">
                                Connection information is correct
                            </div>`
                        );
                    }else{
                        $('#msg').html(
                            `<div class="alert alert-danger" role="alert">
                                Connection information is not correct!
                            </div>`
                        );
                    }
                },
                error: function () {
                    $('#msg').html(
                        `<div class="alert alert-danger" role="alert">
                                Connection information is not correct!
                            </div>`
                    );
                }
            });
        });
    });
EOL;
if(!$model->isNewRecord) {
    $this->registerJs(
        $JS,
        $this::POS_READY
    );
}
?>

views/hotel-apis/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\HotelApisSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="hotel-apis-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'hotel_apis_id') ?>

    <?= $form->field($model, 'hotel_id') ?>

    <?= $form->field($model, 'hotel_name') ?>

    <?= $form->field($model, 'api_key') ?>

    <?= $form->field($model, 'beds24_room_map') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/hotel-apis/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\HotelApis */

$this->title = 'Create Hotel Apis';
$this->params['breadcrumbs'][] = ['label' => 'Hotel Apis', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="hotel-apis-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/hotel-apis/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel app\models\HotelApisSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Hotel Apis';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="hotel-apis-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Hotel Apis', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'hotel_id',
                'headerOptions' => ['style' => 'width:5%'],
            ],
            [
                'attribute' => 'hotel_name',
                'headerOptions' => ['style' => 'width:10%'],
            ],
            'api_key',
            [
                'attribute' => 'beds24_room_map',
                'headerOptions' => ['style' => 'width:35%'],
            ],
             [
                'attribute' => 'status',
                'value' => function ($data) {
                    return ucfirst($data->status); 
                },
            ],
            [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{view} {update} {delete} {sync}',  
                'buttons' => [
                    'sync' => function($url, $model, $key) {     
                        return Html::a('', Url::to(["/web-api/sync",'id'=>$model->hotel_apis_id], true),["class"=>"glyphicon glyphicon-triangle-right"]);
                    }
                ]
            ]
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

views/hotel-apis/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\HotelApis */

$this->title = 'Update Hotel Apis: ' . $model->hotel_name;
$this->params['breadcrumbs'][] = ['label' => 'Hotel Apis', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->hotel_name, 'url' => ['view', 'id' => $model->hotel_apis_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="alert alert-info">
    (zhavroad price) = (price rate) * (beds24 price)
</div>
<div class="hotel-apis-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/hotel-apis/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\HotelApis */

$this->title = $model->hotel_name;
$this->params['breadcrumbs'][] = ['label' => 'Hotel Apis', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="hotel-apis-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->hotel_apis_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->hotel_apis_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'hotel_apis_id',
            'hotel_id',
            'hotel_name',
            'api_key',
            'beds24_room_map',
            'status'
        ],
    ]) ?>

</div>